// weird data types are returned from the Binance API
export interface Currency {
    askPrice: string,
    askQty: string,
    bidPrice: string,
    bidQty: string,
    closeTime: number,
    count: number,
    firstId: number,
    highPrice: string,
    lastId: number,
    lastPrice: string,
    lastQty: string,
    lowPrice: string,
    openPrice: string,
    openTime: number,
    prevClosePrice: string,
    priceChange: string,
    priceChangePercent: string,
    quoteVolume: string,
    symbol: string,
    volume: string,
    weightedAvgPrice: string,
}